export const ActionTypes = {
    FETCH_STUDENTS: "FETCH_STUDENTS",
    SET_STUDENTS: "SET_STUDENTS",
    SELECTED_STUDENTS: "SELECTED_STUDENTS",
    SET_CLASSES: "SET_CLASSES",
    SET_COURSES: "SET_COURSES",
}